database/database/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from web.views import account, project, part, bushing, interface, link, winding, user, department, fiber, resin, r_and_d, sequenceType,docs
from web.views.load_parts import load_parts, load_interfaces, load_links
from web.views.load_fiber_resin import get_fiber_data, get_resin_data
from django.urls import path, re_path
from django.views.generic import RedirectView
from django.views.static import serve
import os



urlpatterns = [
    re_path(r'^documentation/(?P<path>.*)$', docs.serve_docs, name='documentation'),
    path('updateDoc/', docs.upload_docs, name='updateDoc'),

    path('', account.home, name='home0'),
    # path('accounts/login/', account.loginA),
    path('login/', account.login, name='login'),
    path('logout/', account.logout, name='logout'),
    path('img/code/', account.img_code, name='img_code'),
    path('home/', account.home, name='home'),
    # path('home/', log.log_list),
    path('upload/', account.upload, name='upload'),
    path('check/', account.check, name='check'),
    path('changePassword/<int:aid>/', account.changePassword, name='changePassword'),
    path('myLog/', account.user_log, name='user_log'),

    path('fiber/list/', fiber.fiber_list, name='fiber_list'),
    path('fiber/valid/', fiber.fiber_valid, name='fiber_valid'),
    path('fiber/add/', fiber.fiber_add, name='fiber_add'),
    path('fiber/add-multiple/', fiber.fiber_add_multiple, name='fiber_add_multiple'),
    path('fiber/edit/<int:aid>/', fiber.fiber_edit, name='fiber_edit'),
    path('fiber/delete/', fiber.fiber_delete, name='fiber_delete'),
    path('fiber/modify-multiple/', fiber.fiber_modify_multiple, name='fiber_modify_multiple'),

    path('resin/list/', resin.resin_list, name='resin_list'),
    path('resin/list-mechanical-properties/', resin.resin_list_mechanical_properties, name='resin_list_mechanical_properties'),
    path('resin/list-thermophysical-toughness-properties/', resin.resin_list_thermophysical_toughness_properties, name='resin_list_thermophysical_toughness_properties'),
    path('resin/valid/', resin.resin_valid, name='resin_valid'),
    path('resin/valid-mechanical-properties/', resin.resin_valid_mechanical_properties, name='resin_valid_mechanical_properties'),
    path('resin/valid-thermophysical-toughness-properties/', resin.resin_valid_thermophysical_toughness_properties, name='resin_valid_thermophysical_toughness_properties'),
    path('resin/add/', resin.resin_add, name='resin_add'),
    path('resin/add-multiple/', resin.resin_add_multiple, name='resin_add_multiple'),
    path('resin/add-mechanical-properties/', resin.resin_add_mechanical_properties, name='resin_add_mechanical_properties'),
    path('resin/add-thermophysical-toughness-properties/', resin.resin_add_thermophysical_toughness_properties, name='resin_add_thermophysical_toughness_properties'),
    path('resin/edit/<int:aid>/', resin.resin_edit, name='resin_edit'),
    path('resin/delete/', resin.resin_delete, name='resin_delete'),
    path('resin/modify-multiple/', resin.resin_modify_multiple, name='resin_modify_multiple'),
    path('resin/modify-mechanical-properties/', resin.resin_modify_mechanical_properties, name='resin_modify_mechanical_properties'),
    path('resin/modify-thermophysical-toughness-properties/', resin.resin_modify_thermophysical_toughness_properties, name='resin_modify_thermophysical_toughness_properties'),

    path('r_and_d/list/', r_and_d.r_and_d_list, name='r_and_d_list'),
    path('r_and_d/valid/', r_and_d.r_and_d_valid, name='r_and_d_valid'),
    path('r_and_d/add/', r_and_d.r_and_d_add, name='r_and_d_add'),
    path('r_and_d/edit/<int:aid>/', r_and_d.r_and_d_edit, name='r_and_d_edit'),
    path('r_and_d/delete/', r_and_d.r_and_d_delete, name='r_and_d_delete'),
    path('r_and_d/load-fiber-resin/', get_fiber_data, name='get_fiber_data'),
    path('r_and_d/load-fiber-resin/', get_resin_data, name='get_resin_data'),
    path('get-fiber-details/<int:fiber_id>/', get_fiber_data, name='get_fiber_data'),
    path('get-resin-details/<int:resin_id>/', get_resin_data, name='get_resin_data'),

    path('project/list/', project.project_list, name='project_list'),
    path('project/valid/', project.project_valid, name='project_valid'),
    path('project/add/', project.project_add, name='project_add'),
    path('project/edit/<int:aid>/', project.project_edit, name='project_edit'),
    path('project/delete/', project.project_delete, name='project_delete'),
    path('project/upload/', project.upload_file_project, name='upload_file_project'),
    path('project/pdf/', project.download_projects_pdf, name='download_projects_pdf'),

    path('part/list/', part.part_list, name='part_list'),
    path('part/list-doc/', part.part_list_doc, name='part_list_doc'),
    path('part/valid/', part.part_valid, name='part_valid'),
    path('part/valid-doc/', part.part_valid_doc, name='part_valid_doc'),
    path('part/add/', part.part_add, name='part_add'),
    path('part/edit/<int:aid>/', part.part_edit, name='part_edit'),
    path('part/edit-doc/<int:aid>/', part.part_edit_doc, name='part_edit_doc'),
    path('part/delete/', part.part_delete, name='part_delete'),
    path('part/upload/', part.upload_file_part, name='upload_file_part'),
    path('part/pdf/', part.download_parts_pdf, name='download_parts_pdf'),

    path('bushing/list/', bushing.bushing_list, name='bushing_list'),
    path('bushing/valid/', bushing.bushing_valid, name='bushing_valid'),
    path('bushing/add/', bushing.bushing_add, name='bushing_add'),
    path('bushing/edit/<int:aid>/', bushing.bushing_edit, name='bushing_edit'),
    path('bushing/delete/', bushing.bushing_delete, name='bushing_delete'),
    path('bushing/load-parts/', load_parts, name='load_parts'),
    path('bushing/add-multiple/', bushing.bushing_add_multiple, name='bushing_add_multiple'),
    path('bushing/modify-multiple/', bushing.bushing_modify_multiple, name='bushing_modify_multiple'),
    path('bushing/upload/', bushing.upload_file_bushing, name='upload_file_bushing'),
    path('bushing/pdf/', bushing.download_bushings_pdf, name='download_bushings_pdf'),

    path('interface/list/', interface.interface_list, name='interface_list'),
    path('interface/valid/', interface.interface_valid, name='interface_valid'),
    path('interface/add/', interface.interface_add, name='interface_add'),
    path('interface/edit/<int:aid>/', interface.interface_edit, name='interface_edit'),
    path('interface/delete/', interface.interface_delete, name='interface_delete'),
    path('interface/load-parts/', load_parts, name='load_parts'),
    path('interface/add-multiple/', interface.interface_add_multiple, name='interface_add_multiple'),
    path('interface/modify-multiple/', interface.interface_modify_multiple, name='interface_modify_multiple'),
    path('interface/upload/', interface.upload_file_interface, name='upload_file_interface'),
    path('interface/pdf/', interface.download_interfaces_pdf, name='download_interfaces_pdf'),

    path('link/list/', link.link_list, name='link_list'),
    path('link/valid/', link.link_valid, name='link_valid'),
    path('link/add/', link.link_add, name='link_add'),
    path('link/edit/<int:aid>/', link.link_edit, name='link_edit'),
    path('link/delete/', link.link_delete, name='link_delete'),
    path('link/load-parts/', load_parts, name='load_parts'),
    path('link/load-interface/', load_interfaces, name='load_interfaces'),
    path('link/add-multiple/', link.link_add_multiple, name='link_add_multiple'),
    path('link/modify-multiple/', link.link_modify_multiple, name='link_modify_multiple'),
    path('link/upload/', link.upload_file_link, name='upload_file_link'),
    path('link/pdf/', link.download_links_pdf, name='download_links_pdf'),


    path('winding/list/', winding.winding_list, name='winding_list'),
    path('winding/valid/', winding.winding_valid, name='winding_valid'),
    path('winding/add/', winding.winding_add, name='winding_add'),
    path('winding/edit/<int:aid>/', winding.winding_edit, name='winding_edit'),
    path('winding/delete/', winding.winding_delete, name='winding_delete'),
    path('winding/load-parts/', load_parts, name='load_parts'),
    path('winding/load-interface/', load_interfaces, name='load_interfaces'),
    path('winding/load-link/', load_links, name='load_links'),
    path('winding/add-multiple/', winding.winding_add_multiple, name='winding_add_multiple'),
    path('winding/modify-multiple/', winding.winding_modify_multiple, name='winding_modify_multiple'),

    path('user/list/', user.user_list, name='user_list'),
    path('user/list-read/', user.user_list_read, name='user_list_read'),
    path('user/edit/<int:aid>/', user.user_edit, name='user_edit'),
    path('user/delete/', user.user_delete, name='user_delete'),
    path('user/add-multiple/', user.user_add_multiple, name='user_add_multiple'),
    path('user/modify-multiple/', user.user_modify_multiple, name='user_modify_multiple'),

    path('department/list/', department.department_list, name='department_list'),
    path('department/list-read/', department.department_list_read, name='department_list_read'),
    path('department/edit/<int:aid>/', department.department_edit, name='department_edit'),
    path('department/delete/', department.department_delete, name='department_delete'),
    path('department/add-multiple/', department.department_add_multiple, name='department_add_multiple'),
    path('department/modify-multiple/', department.department_modify_multiple, name='department_modify_multiple'),

    path('sequenceType/list/', sequenceType.sequenceType_list, name='sequenceType_list'),
    path('sequenceType/valid/', sequenceType.sequenceType_valid, name='sequenceType_valid'),
    path('sequenceType/edit/<int:aid>/', sequenceType.sequenceType_edit, name='sequenceType_edit'),

database/web/views/department.py
from django.shortcuts import render, redirect, HttpResponse
from django.http import JsonResponse
from django import forms
from django.forms import modelformset_factory
from django.db.models import Count
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas

from web import models
import django_filters

class DepartmentFilter(django_filters.FilterSet):
    # departmentName = django_filters.CharFilter(lookup_expr='icontains')

    class Meta:
        model = models.Department
        fields = {
            'title': ['icontains'],
        }

def department_list(request):
    """ list of department """

    departments = models.Department.objects.annotate(employee_count=Count('user'))
    return render(request, 'department/department_list.html', {'departments': departments})

def department_list_read(request):
    """ list of department """

    departments = models.Department.objects.annotate(employee_count=Count('user'))
    return render(request, 'department/department_list_read.html', {'departments': departments})

class DepartmentModelForm(forms.ModelForm):
    class Meta:
        model = models.Department
        fields = ['title',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, filed_object in self.fields.items():
            filed_object.widget.attrs = {"class": "form-control"}


DepartmentFormSet = modelformset_factory(
    models.Department,
    form=DepartmentModelForm,
    extra=1  
)


def department_add(request):
    if request.method == "GET":
        form = DepartmentModelForm()
        return render(request, 'department/department_form.html', {"form": form})

    form = DepartmentModelForm(data=request.POST)
    if not form.is_valid():
        return render(request, 'department/department_form.html', {"form": form})

    # form.save()
    department = form.save(commit=False)
    department.user = models.User.objects.filter(id=request.info_dict['id']).first()  
    department.save()
    return redirect('/department/list/')


def department_add_multiple(request):
    formset = DepartmentFormSet(queryset=models.Department.objects.none())
    # interfaceError = None

    if request.method == 'POST':
        formset = DepartmentFormSet(request.POST)

        if formset.is_valid() : 
            instances = formset.save(commit=False)
            for instance in instances:
                instance.user = models.User.objects.filter(id=request.info_dict['id']).first()  
                instance.save()
            return redirect('/department/list/')  # Replace with your redirect URL
        else:
            # Handle formset or project_part_form validation errors here
            print(formset.errors)

    return render(request, 'department/department_add_multiple.html', {
        'formset': formset,
    })

def department_modify_multiple(request):
    # Get filtered data
    department_filter = DepartmentFilter(request.GET, queryset=models.Department.objects.all())
    
    # Define form set
    DepartmentFormSet = modelformset_factory(models.Department, form=DepartmentModelForm, extra=0)
    
    if request.method == 'POST':
        formset = DepartmentFormSet(request.POST)
        if formset.is_valid():
            instances = formset.save(commit=False)
            
            for instance in instances:
                instance.user = models.User.objects.filter(id=request.info_dict['id']).first()  
                instance.save()
            return redirect('/department/list/')
    else:
        formset = DepartmentFormSet(queryset=department_filter.qs)

    return render(request, 'department/department_modify_multiple.html', {
        'filter': department_filter,
        'formset': formset,
    })


class DepartmentEditModelForm(forms.ModelForm):
    class Meta:
        model = models.Department
        fields = ['title',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for name, filed_object in self.fields.items():
            filed_object.widget.attrs = {"class": "form-control"}


def department_edit(request, aid):
    department_object = models.Department.objects.filter(id=aid).first()

    if request.method == "GET":
        form = DepartmentEditModelForm(instance=department_object)
        return render(request, 'department/department_form.html', {"form": form})

    form = DepartmentEditModelForm(instance=department_object, data=request.POST)
    if not form.is_valid():
        return render(request, 'department/department_form.html', {"form": form})

    # form.save()
    department = form.save(commit=False)
    department.user = models.User.objects.filter(id=request.info_dict['id']).first()  
    department.save()

    return redirect('/department/list/')


def department_delete(request):
    aid = request.GET.get("aid")
    # models.Department.objects.filter(id=aid).delete()
    department = models.Department.objects.filter(id=aid).first()
    if department:
        department.user = models.User.objects.filter(id=request.info_dict['id']).first()  
        department.delete()

    return JsonResponse({"status": True})


def department_delete_mult(request):
    aid = request.GET.get("aid")
    if not aid:
        return JsonResponse({"status": False, "error": "ID cannot be empty"})

    try:
        department = models.Department.objects.get(id=aid)
        # department.delete()
        if department:
            department.user = models.User.objects.filter(id=request.info_dict['id']).first()  
            department.delete()

        return JsonResponse({"status": True})
    except models.Department.DoesNotExist:
        return JsonResponse({"status": False, "error": "Department not found"})

database/web/templates/user/user_add_multiple.html
{% extends 'layout.html' %}

{% block content %}
<div class="panel panel-default" id="cont">
    <div class="panel-heading"><span class="glyphicon glyphicon-indent-right" aria-hidden="true"></span> Add Multiple Users
        <details>
            <summary>
                <span class="glyphicon glyphicon-question-sign" aria-hidden="true" id="help-title">
                    Help
                </span>
            </summary>        
            <div id="help-content">
                Here, we can enter the value of each attribute manually or by batch copying and pasting. <br>
                Click the <a id="help-btn-add">Add User</a> button to add a row.<br>
                Click the <a id="help-btn-remove">Remove</a> button to clear the corresponding row.<br>
                Click the <a id="help-btn-save">Save</a> button to save the data to the database.<br>
            </div>
        </details>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            <div class="row">
                {{ formset.management_form }}
                <table class="table table-bordered" id="user-table">
                    <thead>
                        <tr>
                            <th>Username</th>
                            <th style="width: 40%;">Department</th>
                            <th style="width: 100px;">Operation</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for field in formset %}
                            <tr class="user-form">
                                <td contenteditable="true">{{ field.username }}<span style="color: red;">{{ field.errors.0 }}</span></td>
                                <td contenteditable="true">{{ field.depart }}<span style="color: red;">{{ field.errors.0 }}</span></td>
                                <td class="text-center"> <button type="button" class="btn btn-danger remove-form">Remove</button> </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="col-sm-offset-8 col-sm-12">
                            <button type="button" id="add-user" class="btn btn-secondary" style="width: 15%;">Add User</button>
                            <button type="submit" class="btn btn-primary" style="width: 10%; margin-left: 6%;">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
<script type="text/javascript">
    $(document).ready(function() {
        $('#add-user').click(function() {
            var formCount = $('#id_form-TOTAL_FORMS').val();
            var newForm = $('.user-form:first').clone(true).removeClass('user-form');
            newForm.find('input, select').each(function() {
                var name = $(this).attr('name').replace('-0-', '-' + formCount + '-');
                var id = 'id_' + name;
                $(this).attr({'name': name, 'id': id}).val('');
            });
            newForm.find('td:last').html('<button type="button" class="btn btn-danger remove-form">Remove</button>');
            $('#user-table tbody').append(newForm);
            $('#id_form-TOTAL_FORMS').val(parseInt(formCount) + 1);
        });

        $(document).on('click', '.remove-form', function() {
            var $row = $(this).closest('tr');
            if ($row.index() === 0) {
                // console.log("me")
                // console.log($row.index())
                // Clear the content of the first row
                $row.find('input').val('');
            } else {
                console.log($row.index())
                if ($('#user-table tbody tr').length > 1) {
                    $row.remove();
                    var formCount = $('#id_form-TOTAL_FORMS').val();
                    $('#id_form-TOTAL_FORMS').val(parseInt(formCount) - 1);
                    // Reindex all table rows
                    $('#user-table tbody tr').each(function(index) {
                        $(this).find('input').each(function() {
                            var name = $(this).attr('name').replace(/-\d+-/, '-' + index + '-');
                            var id = 'id_' + name;
                            $(this).attr({'name': name, 'id': id});
                        });
                    });
                }
            }
        });
    });
</script>

{% endblock %}

{% block css %}
<style>
    #cont {
        width: 50%;
        margin: auto;
        margin-bottom: 100px;
    }
    
    #id_project, #id_department, input[type="text"] {
        width: 100%; 
        padding: 8px; 
        margin: 0px 0; 
        display: inline-block;
        border: 1px solid #ccc; 
        border-radius: 4px; 
        box-sizing: border-box; 
    }
</style>
{% endblock %}

database/web/templates/user/user_form.html
{% extends 'layout.html' %}
{% block content %}
<div class="panel panel-default" style="margin-bottom: 100px; width: 50%; margin-left: 25%;">
    <div class="panel-heading"><span class="glyphicon glyphicon-indent-right" aria-hidden="true"></span> Edit User Information
        <details>
            <summary>
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true" id="help-title">
                Help
            </span>
            </summary>        
            <div id="help-content">
                Here, we can edit the value of each attribute manually or by copying and pasting. <br>
                Click the <a id="help-btn-save">Save</a> button to save the data to the database.<br>
            </div>
        </details>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" method="post" novalidate>
            {% csrf_token %}
            <div class="row">
                {% for field in form %}
                    <div class="col-xs-12">
                        <div class="form-group" style="margin-bottom: 25px;">
                            <label class="col-sm-2 control-label">{{ field.label }}</label>
                            <div class="col-sm-10" style="position: relative">
                                {{ field }}
                                <span style="color: red;position: absolute;">{{ field.errors.0 }}</span>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-xs-12">
                        <div class="col-sm-offset-6 col-sm-10">
                            <button type="submit" class="btn btn-primary" style="width: 200px;">Save</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>

{% endblock %}

database/web/templates/user/user_list.html
{% extends 'layout.html' %}
{% block content %}
<div id="cont">
    <div style="margin-bottom: 10px">
        <a class="btn btn-success" href="/user/add-multiple/">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> New User
        </a>
    </div>  
    <h3>User List:</h3>
    <details>
        <summary>
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true" id="help-title">
                Help
            </span>
        </summary>        
        <div id="help-content">
            Here, we can check the value of each record. <br>
            Click the <a id="help-btn-upload">New User</a> button to jump to create new Users records.<br>
            We can use <a id="help-btn-filter">Filter</a> to select some specific records.<br>
            Click the <a id="help-btn-filter">Reset</a> button to reset the filter to the original state.<br>
            Click the <a id="help-btn-edit">Edit</a> button to modify the data of the corresponding row.<br>
            Click the <a id="help-btn-remove">Delete</a> button to delete the corresponding row.<br>
        </div>
    </details>
    <form method="get" id="filterForm" class="from_f">
        {{ filter.form.as_p }}
        <button type="submit" id="btnf1" name="filter">Filter</button>
        <button type="reset" id="resetButton" class="btnf2">Reset</button>
        <a class="btn btn-success" href="/user/modify-multiple/" id="btnmore">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> Modify User List
        </a>
    </form>
    <div id="loading" class="loading-overlay">
        <div class="spinner"></div>
        <a id="loadingtext"> Loading </a>
    </div>
    <div id="tableContainer" >
        <table class="table table-bordered" id="normalTable">
            <thead>
                <tr>
                    <th style="width: 50%;">User Name</th>
                    <th style="width: 30%;">Department</th>
                    <th style="width: 20%;">Operations</th>
                </tr>
            </thead>
            <tbody>
                {% for row in filter.qs %}
                    <tr>
                        <td>{{ row.username }}</td>
                        <td>{{ row.depart }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/user/edit/{{ row.id }}/" style="width: 40px; text-align: center; margin-bottom: 5px;"> Edit </a>
                            <input type="button" value="Delete" class="btn btn-danger btn-xs" style="width: 50px; text-align: center; margin-bottom: 5px;"
                                onclick="deleteAction({{ row.id }});"/>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="3" class="text-center" style="font-size: large;">No data found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="alert alert-danger alert-dismissible fade in" role="alert">
            <button type="button" class="close"></button>
            <h4>Are you sure you want to delete it?</h4>
            <p style="margin: 20px 0;">After deletion, all related data associated with it will be deleted. Are you sure you want to continue?</p>
            <p>
                <button type="button" class="btn btn-danger" onclick="confirmDelete()">Confirm</button>
                <button type="button" class="btn btn-default" onclick="cancelDelete()">Cancel</button>
            </p>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
        
    // ID currently to be deleted
    DELETE_ID = 0;
    function deleteAction(id) {
        DELETE_ID = id;
        $('#myModal').modal('show');
    }

    function confirmDelete() {
        // Send request to backend DELETE_ID -> Delete
        // Page refresh
        // /project/delete/?aid=12
        $.ajax({
            url: "/user/delete/",
            type: "GET",
            data: {
                aid: DELETE_ID
            },
            dataType: "JSON",
            success: function (res) {
                // {status: true} -> obj
                if (res.status) {
                    // Deletion successful, refresh the page
                    location.reload()
                } else {
                    alert(res.error);
                }
            }
        })
    }

    function cancelDelete() {
        DELETE_ID = 0;
        $('#myModal').modal('hide');
    }
</script>
{% endblock %}

{% block css %}
<style>
    #cont {
        width: 50%;
        margin: auto;
        margin-bottom: 100px;
    }
   
    #id_depart, input[type="text"] {
        width: 100%; 
        padding: 8px; 
        margin: 0px 0; 
        display: inline-block;
        border: 1px solid #ccc; 
        border-radius: 4px; 
        box-sizing: border-box; 
    }
    #btnmore {
        width: 200px; 
        background-color: #49b7be; 
        color: white; 
        padding: 5px 10px; 
        cursor: pointer; 
        height: 30px;
        position: absolute;
        right: 26%;
        margin-top: 8px;
        border: none; 
        border-radius: 4px;
        cursor: pointer; 
        font-size: large;
    }
    #btnmore:hover {
        background-color: #378488;
    }
 
   
</style>
{% endblock %}

database/web/templates/user/user_list_read.html
{% extends 'layout.html' %}
{% block content %}
<div id="cont">
    <h3>User List:</h3>
    <details>
        <summary>
            <span class="glyphicon glyphicon-question-sign" aria-hidden="true" id="help-title">
                Help
            </span>
        </summary>        
        <div id="help-content">
            Here, we can read the value of each record. <br>
            We can use <a id="help-btn-filter">Filter</a> to select some specific records.<br>
            Click the <a id="help-btn-filter">Reset</a> button to reset the filter to the original state.<br>
            <!-- Click the Download PDF button to download the displayed data(after filtering) as a pdf document.<br> -->
        </div>
    </details>
    <form method="get" id="filterForm" class="from_f">
        {{ filter.form.as_p }}
        <button type="submit" id="btnf1" name="filter">Filter</button>
        <button type="reset" id="resetButton" class="btnf2">Reset</button>
        <!-- <a id="download" href="{% url 'download_projects_pdf' %}?{{ request.GET.urlencode }}">Download PDF</a> -->
    </form>
    <div id="loading" class="loading-overlay">
        <div class="spinner"></div>
        <a id="loadingtext"> Loading </a>
    </div>
    <div id="tableContainer" >
        <table class="table table-bordered" id="normalTable">
            <thead>
                <tr>
                    <th style="width: 50%;">User Name</th>
                    <th style="width: 50%;">Department</th>
                </tr>
            </thead>
            <tbody>
                {% for row in filter.qs %}
                    <tr>
                        <td>{{ row.username }}</td>
                        <td>{{ row.depart }}</td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2" class="text-center" style="font-size: large;">No data found.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>


{% endblock %}

{% block js %}
<script>
</script>
{% endblock %}

{% block css %}
<style>
    #cont {
        width: 50%;
        margin: auto;
        margin-bottom: 100px;
    }
    
    #id_depart, input[type="text"] {
        width: 100%; 
        padding: 8px; 
        margin: 0px 0; 
        display: inline-block;
        border: 1px solid #ccc; 
        border-radius: 4px; 
        box-sizing: border-box; 
    }
 
   
</style>
{% endblock %}